package nlu

// Foreign-city vocabulary for international flights.
//
// Source: 780's own client bundle. The international search form resolves
// cities entirely client-side (typing in it fires no network request), so the
// full IATA -> Persian-name map ships inside the JS. That map is the
// authoritative vocabulary — it is what 780's own autocomplete matches
// against — and it avoids the api.780.ir authorization wall entirely.
//
// Only NON-Iranian cities live here. Iranian cities stay in cities.go, which
// owns their domestic IATA codes; keeping them out of this table is what makes
// "is this trip international?" answerable by a simple lookup (see
// hasForeignEndpoint). Note that a few Iranian cities appear in 780's
// international map too (IKA, MHD, SYZ, ...) — they are deliberately dropped
// here so their presence can never flip a domestic search to international.
//
// ⚠️ Names that are also ordinary Persian words are deliberately EXCLUDED,
// because matching is whole-word against free-form speech: "رم" (Rome) is also
// the verb "رم کردن", "نیس" (Nice) is colloquial "نیست", "کبک" (Quebec) is
// also the bird, "امان" (Amman) is an everyday word. Including them would turn
// ordinary sentences into international flight searches. The full exclusion
// list and the reasoning live in the commit that added this file; when adding
// a city later, apply the same test: could a Persian speaker say this word
// without meaning the city?
var intlCityEntries = []cityEntry{
	{City{"آتلانتا", "ATL"}, []string{"آتلانتا"}},
	{City{"آدلاید", "ADL"}, []string{"آدلاید"}},
	{City{"آرلینگتون", "DCA"}, []string{"آرلینگتون"}},
	{City{"آرهوس", "AAR"}, []string{"آرهوس"}},
	{City{"آستین", "AUS"}, []string{"آستین"}},
	{City{"آکرون", "CAK"}, []string{"آکرون"}},
	{City{"آگوستا", "AGS"}, []string{"آگوستا"}},
	{City{"آل فوجایراه", "FJR"}, []string{"آل فوجایراه"}},
	{City{"آلبانی", "ALB"}, []string{"آلبانی"}},
	{City{"آمریتسار", "ATQ"}, []string{"آمریتسار"}},
	{City{"آمستردام", "AMS"}, []string{"آمستردام"}},
	{City{"آنتالیا", "AYT"}, []string{"آنتالیا"}},
	{City{"آنتورپ", "ANR"}, []string{"آنتورپ"}},
	{City{"آنتیگوا", "ANU"}, []string{"آنتیگوا"}},
	{City{"آندورا لا ولا", "ALV"}, []string{"آندورا لا ولا"}},
	{City{"آنکارا", "ESB"}, []string{"آنکارا"}},
	{City{"ابوظبی", "AUH"}, []string{"ابو ظبی", "ابوظبی"}},
	{City{"اتلانتیک سیتی", "ACY"}, []string{"اتلانتیک سیتی"}},
	{City{"ادمونتون", "YEA"}, []string{"ادمونتون"}},
	{City{"اربیل", "EBL"}, []string{"اربیل"}},
	{City{"ازمیر", "ADB"}, []string{"ازمیر"}},
	{City{"اسپارتا", "ISE"}, []string{"اسپارتا"}},
	{City{"اسپرینگ فیلد", "SGF"}, []string{"اسپرینگ فیلد"}},
	{City{"اسپن", "ASE"}, []string{"اسپن"}},
	{City{"اسپوکان", "GEG"}, []string{"اسپوکان"}},
	{City{"استانبول", "IST"}, []string{"اسلامبول", "استانبول"}},
	{City{"اسکندریه", "HBE"}, []string{"اسکندریه"}},
	{City{"اسوان", "ASW"}, []string{"اسوان"}},
	{City{"اشویل", "AVL"}, []string{"اشویل"}},
	{City{"اقصر", "LXR"}, []string{"اقصر"}},
	{City{"ال یودید", "XJD"}, []string{"ال یودید"}},
	{City{"البورگ", "AAL"}, []string{"البورگ"}},
	{City{"الجزیره", "ALG"}, []string{"الجزیره"}},
	{City{"العین", "AAN"}, []string{"العین"}},
	{City{"الکساندریا", "AEX"}, []string{"الکساندریا"}},
	{City{"الکو", "EKO"}, []string{"الکو"}},
	{City{"النتاون", "ABE"}, []string{"النتاون"}},
	{City{"انکوریج", "ANC"}, []string{"انکوریج"}},
	{City{"اوتاوا", "YOW"}, []string{"اوتاوا"}},
	{City{"اودسا", "ODS"}, []string{"اودسا"}},
	{City{"اودنسا", "ODE"}, []string{"اودنسا"}},
	{City{"اورلاندو", "MCO"}, []string{"اورلاندو"}},
	{City{"اورنج کانتی", "SNA"}, []string{"اورنج کانتی"}},
	{City{"اوژن", "EUG"}, []string{"اوژن"}},
	{City{"اوستنده", "OST"}, []string{"اوستنده"}},
	{City{"اوشوایا", "USH"}, []string{"اوشوایا"}},
	{City{"اوکلند", "OAK"}, []string{"اوکلند"}},
	{City{"اوگدن", "OGD"}, []string{"اوگدن"}},
	{City{"اوندژیوا", "VPE"}, []string{"اوندژیوا"}},
	{City{"ایروان", "EVN"}, []string{"ایروان"}},
	{City{"ایگل", "EGE"}, []string{"ایگل"}},
	{City{"اینسبروک", "INN"}, []string{"اینسبروک"}},
	{City{"باتومی", "BUS"}, []string{"باتومی"}},
	{City{"باتون روژ", "BTR"}, []string{"باتون روژ"}},
	{City{"باربودا", "BBQ"}, []string{"باربودا"}},
	{City{"بارسلونا", "BCN"}, []string{"بارسلونا"}},
	{City{"باکو", "GYD"}, []string{"باکو"}},
	{City{"بالتیمور", "BWI"}, []string{"بالتیمور"}},
	{City{"بامیان", "BIN"}, []string{"بامیان"}},
	{City{"بانکوک", "BKK"}, []string{"بانکوک"}},
	{City{"بانیالوکا", "BNX"}, []string{"بانیالوکا"}},
	{City{"بتنا", "BLJ"}, []string{"بتنا"}},
	{City{"بجیا", "BJA"}, []string{"بجیا"}},
	{City{"بربنک", "BUR"}, []string{"بربنک"}},
	{City{"برلین", "BER"}, []string{"برلین"}},
	{City{"بروکسل", "BRU"}, []string{"بروکسل"}},
	{City{"برونزویک", "BRZ"}, []string{"برونزویک"}},
	{City{"بریج تاون", "BGI"}, []string{"بریج تاون"}},
	{City{"بریزبن", "BNE"}, []string{"بریزبن"}},
	{City{"بریستول", "BRS"}, []string{"بریستول"}},
	{City{"بصره", "BSR"}, []string{"بصره"}},
	{City{"بغداد", "BGW"}, []string{"بغداد"}},
	{City{"بگرام", "OAI"}, []string{"بگرام"}},
	{City{"بلیز", "BZE"}, []string{"بلیز"}},
	{City{"بلینگهام", "BLI"}, []string{"بلینگهام"}},
	{City{"بمبئی", "BOM"}, []string{"بمبئی", "مومبای"}},
	{City{"بمیدجی", "BJI"}, []string{"بمیدجی"}},
	{City{"بنگالورو", "BLR"}, []string{"بنگالورو"}},
	{City{"بو سعده", "BUJ"}, []string{"بو سعده"}},
	{City{"بوئنوس آیرس", "BUE"}, []string{"بوئنوس آیرس"}},
	{City{"بوستون", "BOS"}, []string{"بوستون"}},
	{City{"بوفالو", "BUF"}, []string{"بوفالو"}},
	{City{"بولهد سیتی", "IFP"}, []string{"بولهد سیتی"}},
	{City{"بیرمنگام", "BHX"}, []string{"بیرمنگام"}},
	{City{"بیروت", "BEY"}, []string{"بیروت"}},
	{City{"بیسکرا", "BSK"}, []string{"بیسکرا"}},
	{City{"پاراکو", "PKO"}, []string{"پاراکو"}},
	{City{"پاریس", "CDG"}, []string{"پاریس"}},
	{City{"پاسکو", "PSC"}, []string{"پاسکو"}},
	{City{"پئوریا", "PIA"}, []string{"پئوریا"}},
	{City{"پروو", "PVU"}, []string{"پروو"}},
	{City{"پکن", "PEK"}, []string{"پکن", "بیجینگ"}},
	{City{"پلاسنسیا", "PLJ"}, []string{"پلاسنسیا"}},
	{City{"پوبلو", "PUB"}, []string{"پوبلو"}},
	{City{"پورتلند", "PDX"}, []string{"پورتلند"}},
	{City{"پوکت", "HKT"}, []string{"پوکت"}},
	{City{"پیترزبورگ", "PSG"}, []string{"پیترزبورگ"}},
	{City{"تاریجا", "TJA"}, []string{"تاریجا"}},
	{City{"تامپری", "TMP"}, []string{"تامپری"}},
	{City{"تتربورو", "TEB"}, []string{"تتربورو"}},
	{City{"ترابزون", "TZX"}, []string{"ترابزون"}},
	{City{"تراورس سیتی", "TVC"}, []string{"تراورس سیتی"}},
	{City{"ترنتون", "TTN"}, []string{"ترنتون"}},
	{City{"تفلیس", "TBS"}, []string{"تبلیسی", "تفلیس"}},
	{City{"تلوراید", "TEX"}, []string{"تلوراید"}},
	{City{"تمپا", "TPA"}, []string{"تمپا"}},
	{City{"تمنراست", "TMR"}, []string{"تمنراست"}},
	{City{"تورکو", "TKU"}, []string{"تورکو"}},
	{City{"توسان", "TUS"}, []string{"توسان"}},
	{City{"تیارت", "TID"}, []string{"تیارت"}},
	{City{"تیرانا", "TIA"}, []string{"تیرانا"}},
	{City{"جاپلین", "JLN"}, []string{"جاپلین"}},
	{City{"جزیره پنانگ", "PEN"}, []string{"جزیره پنانگ"}},
	{City{"جکسنویل", "JAX"}, []string{"جکسنویل"}},
	{City{"جلال آباد", "JAA"}, []string{"جلال آباد"}},
	{City{"جورج تاون", "GGT"}, []string{"جورج تاون"}},
	{City{"جورجیا", "AHN"}, []string{"جورجیا"}},
	{City{"جوهور بهرو", "JHB"}, []string{"جوهور بهرو"}},
	{City{"جیامری", "LWN"}, []string{"جیامری"}},
	{City{"چتانوگا", "CHA"}, []string{"چتانوگا"}},
	{City{"چنای", "MAA"}, []string{"چنای"}},
	{City{"چنگچینگ", "CKG"}, []string{"چنگچینگ"}},
	{City{"چنگدو", "CTU"}, []string{"چنگدو"}},
	{City{"چیانگ رایی", "CEI"}, []string{"چیانگ رایی"}},
	{City{"چیانگ مای", "CNX"}, []string{"چیانگ مای"}},
	{City{"حلب", "ALP"}, []string{"حلب"}},
	{City{"حیدرآباد", "HYD"}, []string{"حیدرآباد"}},
	{City{"خارکوف", "HRK"}, []string{"خارکوف"}},
	{City{"خجند", "LBD"}, []string{"خجند"}},
	{City{"دالامان", "DLM"}, []string{"دالامان"}},
	{City{"دالس", "DFW"}, []string{"دالس"}},
	{City{"دبی", "DXB"}, []string{"دبی"}},
	{City{"دمشق", "DAM"}, []string{"دمشق"}},
	{City{"دنور", "DEN"}, []string{"دنور"}},
	{City{"دوحه", "DOH"}, []string{"دوحه"}},
	{City{"دورانگو", "DRO"}, []string{"دورانگو"}},
	{City{"دوسلدورف", "DUS"}, []string{"دوسلدورف"}},
	{City{"دوشنبه", "DYU"}, []string{"دوشنبه"}},
	{City{"دوقم", "DQM"}, []string{"دوقم"}},
	{City{"دولوت", "DLH"}, []string{"دولوت"}},
	{City{"دهلی", "DEL"}, []string{"دهلی نو", "نیو دهلی", "دهلی"}},
	{City{"دیانت", "DJG"}, []string{"دیانت"}},
	{City{"دیترویت", "DTT"}, []string{"دیترویت"}},
	{City{"دیتون", "DAY"}, []string{"دیتون"}},
	{City{"دیتونا بیچ", "DAB"}, []string{"دیتونا بیچ"}},
	{City{"دیرالزور", "DEZ"}, []string{"دیرالزور"}},
	{City{"راکفورد", "RFD"}, []string{"راکفورد"}},
	{City{"رالی دورهام", "RDU"}, []string{"رالی دورهام"}},
	{City{"رانگل", "WRG"}, []string{"رانگل"}},
	{City{"رأس الخیمه", "RKT"}, []string{"رأس الخیمه"}},
	{City{"رجاینا", "YQR"}, []string{"رجاینا"}},
	{City{"ردموند", "RDM"}, []string{"ردموند"}},
	{City{"روانوک", "ROA"}, []string{"روانوک"}},
	{City{"روتردام", "RTM"}, []string{"روتردام"}},
	{City{"روچستر", "RST"}, []string{"روچستر"}},
	{City{"ریچموند", "RIC"}, []string{"ریچموند"}},
	{City{"زاپوریژیا", "OZH"}, []string{"زاپوریژیا"}},
	{City{"زالتسبورگ", "SZG"}, []string{"زالتسبورگ"}},
	{City{"ساراستا", "SRQ"}, []string{"ساراستا"}},
	{City{"سارایوو", "SJJ"}, []string{"سارایوو"}},
	{City{"ساکرامنتو", "SMF"}, []string{"ساکرامنتو"}},
	{City{"سالت لیک سیتی", "SLC"}, []string{"سالت لیک سیتی"}},
	{City{"سان خوزه", "SJC"}, []string{"سان خوزه"}},
	{City{"سان فرانسیسکو", "SFO"}, []string{"سان فرانسیسکو"}},
	{City{"سانتا کروس د لا سیرا", "VVI"}, []string{"سانتا کروس د لا سیرا"}},
	{City{"ساوانا", "SAV"}, []string{"ساوانا"}},
	{City{"سطیف", "QSF"}, []string{"سطیف"}},
	{City{"سلیمانیه", "ISU"}, []string{"سلیمانیه"}},
	{City{"سن آنتونیو", "SAT"}, []string{"سن آنتونیو"}},
	{City{"سن دیه گو", "SAN"}, []string{"سن دیه گو"}},
	{City{"سنت پترزبورگ", "LED"}, []string{"سنت پترزبورگ"}},
	{City{"سنت کلود", "STC"}, []string{"سنت کلود"}},
	{City{"سنت لوییس", "STL"}, []string{"سنت لوییس"}},
	{City{"سورات تانی", "URT"}, []string{"سورات تانی"}},
	{City{"سوکر", "SRE"}, []string{"سوکر"}},
	{City{"سویل", "SVQ"}, []string{"سویل"}},
	{City{"سیاتل", "SEA"}, []string{"سیاتل"}},
	{City{"سیتکا", "SIT"}, []string{"سیتکا"}},
	{City{"سیدار سیتی", "CDC"}, []string{"سیدار سیتی"}},
	{City{"سیراکیوز", "SYR"}, []string{"سیراکیوز"}},
	{City{"سینت جورج", "SGU"}, []string{"سینت جورج"}},
	{City{"سینسیناتی", "CVG"}, []string{"سینسیناتی"}},
	{City{"شارجه", "SHJ"}, []string{"شارجه"}},
	{City{"شارلوت", "CLT"}, []string{"شارلوت"}},
	{City{"شانگهای", "SHA"}, []string{"شانگهای"}},
	{City{"شانلی اورفه", "SFQ"}, []string{"شانلی اورفه"}},
	{City{"شرلروآ", "CRL"}, []string{"شرلروآ"}},
	{City{"شرم الشیخ", "SSH"}, []string{"شرم الشیخ"}},
	{City{"شمال لاس وگاس", "VGT"}, []string{"شمال لاس وگاس"}},
	{City{"شنزن", "SZX"}, []string{"شنزن"}},
	{City{"شی آن", "XIY"}, []string{"شی آن"}},
	{City{"شیکاگو", "CHI"}, []string{"شیکاگو"}},
	{City{"صحار", "OHS"}, []string{"صحار"}},
	{City{"صلاله", "SLL"}, []string{"صلاله"}},
	{City{"عجمان", "QAJ"}, []string{"عجمان"}},
	{City{"عقبه", "AQJ"}, []string{"عقبه"}},
	{City{"غردایه", "GHA"}, []string{"غردایه"}},
	{City{"غزه", "GZA"}, []string{"غزه"}},
	{City{"فرانکفورت", "FRA"}, []string{"فرانکفورت"}},
	{City{"فرزنو", "FAT"}, []string{"فرزنو"}},
	{City{"فری پورت", "FPO"}, []string{"فری پورت"}},
	{City{"فلگ استاف", "FLG"}, []string{"فلگ استاف"}},
	{City{"فلورانس", "FLR"}, []string{"فلورانس"}},
	{City{"فلینت", "FNT"}, []string{"فلینت"}},
	{City{"فورت لادردیل", "FLL"}, []string{"فورت لادردیل"}},
	{City{"فورت مایرز", "RSW"}, []string{"فورت مایرز"}},
	{City{"فیربنکس", "FAI"}, []string{"فیربنکس"}},
	{City{"فیلادلفیا", "PHL"}, []string{"فیلادلفیا"}},
	{City{"فینکس", "PHX"}, []string{"فینکس"}},
	{City{"قامشلی", "KAC"}, []string{"قامشلی"}},
	{City{"قاهره", "CAI"}, []string{"قاهره"}},
	{City{"قسطنطنیه", "CZL"}, []string{"قسطنطنیه"}},
	{City{"قندهار", "KDH"}, []string{"قندهار"}},
	{City{"قونیه", "KYA"}, []string{"قونیه"}},
	{City{"کابل", "KBL"}, []string{"کابل"}},
	{City{"کاسان", "BBK"}, []string{"کاسان"}},
	{City{"کالامازو", "AZO"}, []string{"کالامازو"}},
	{City{"کالگری", "YYC"}, []string{"کالگری"}},
	{City{"کانزاس سیتی", "MCI"}, []string{"کانزاس سیتی"}},
	{City{"کاهولویی", "OGG"}, []string{"کاهولویی"}},
	{City{"کایلوا-کونا", "KOA"}, []string{"کایلوا-کونا"}},
	{City{"کایوای", "LIH"}, []string{"کایوای"}},
	{City{"کپنهاگ", "CPH"}, []string{"کپنهاگ"}},
	{City{"کتومبلا", "CBT"}, []string{"کتومبلا"}},
	{City{"کچیکان", "KTN"}, []string{"کچیکان"}},
	{City{"کرابی", "KBV"}, []string{"کرابی"}},
	{City{"کلاگنفورت", "KLU"}, []string{"کلاگنفورت"}},
	{City{"کلرادو اسپرینگز", "COS"}, []string{"کلرادو اسپرینگز"}},
	{City{"کلکته", "CCU"}, []string{"کلکته"}},
	{City{"کلمبوس", "CSG"}, []string{"کلمبوس"}},
	{City{"کلمبیا", "COU"}, []string{"کلمبیا"}},
	{City{"کلیولند", "CLE"}, []string{"کلیولند"}},
	{City{"کوالالامپور", "KUL"}, []string{"کوالا لامپور", "کوالالامپور"}},
	{City{"کوبیجا", "CIJ"}, []string{"کوبیجا"}},
	{City{"کوتائیسی", "KUT"}, []string{"کوتائیسی"}},
	{City{"کوتونو", "COO"}, []string{"کوتونو"}},
	{City{"کوچابامبا", "CBB"}, []string{"کوچابامبا"}},
	{City{"کوچی", "COK"}, []string{"کوچی"}},
	{City{"کودیاک", "ADQ"}, []string{"کودیاک"}},
	{City{"کوردوبا", "COR"}, []string{"کوردوبا"}},
	{City{"کولاب", "TJU"}, []string{"کولاب"}},
	{City{"کوه سامی", "USM"}, []string{"کوه سامی"}},
	{City{"کی کولکر", "CUK"}, []string{"کی کولکر"}},
	{City{"کیف", "IEV"}, []string{"کیف"}},
	{City{"کینگمن", "IGM"}, []string{"کینگمن"}},
	{City{"گابالا", "GBB"}, []string{"گابالا"}},
	{City{"گابورون", "GBE"}, []string{"گابورون"}},
	{City{"گانسیون", "GUC"}, []string{"گانسیون"}},
	{City{"گراتس", "GRZ"}, []string{"گراتس"}},
	{City{"گرند جانکشن", "GJT"}, []string{"گرند جانکشن"}},
	{City{"گرند رپیدز", "GRR"}, []string{"گرند رپیدز"}},
	{City{"گرودنو", "GNA"}, []string{"گرودنو"}},
	{City{"گرینزبورو", "GSO"}, []string{"گرینزبورو"}},
	{City{"گنجه", "KVD"}, []string{"گنجه"}},
	{City{"گوانگجو", "CAN"}, []string{"گوانگجو"}},
	{City{"لاپاز", "LPB"}, []string{"لاپاز"}},
	{City{"لاذقیه", "LTK"}, []string{"لاذقیه"}},
	{City{"لارستان", "LRR"}, []string{"لارستان"}},
	{City{"لاس وگاس", "LAS"}, []string{"لاس وگاس"}},
	{City{"لافایت", "LFT"}, []string{"لافایت"}},
	{City{"لانگ بیچ", "LGB"}, []string{"لانگ بیچ"}},
	{City{"لانگکاوی", "LGK"}, []string{"لانگکاوی"}},
	{City{"لس آنجلس", "LAX"}, []string{"لس آنجلس"}},
	{City{"لندن", "LON"}, []string{"لندن"}},
	{City{"لنکران", "LLK"}, []string{"لنکران"}},
	{City{"لواندا", "LAD"}, []string{"لواندا"}},
	{City{"لوبانگو", "SDD"}, []string{"لوبانگو"}},
	{City{"لووف", "LWO"}, []string{"لووف"}},
	{City{"لیدز برادفورد", "LBA"}, []string{"لیدز برادفورد"}},
	{City{"لیک چارلز", "LCH"}, []string{"لیک چارلز"}},
	{City{"لینز", "LNZ"}, []string{"لینز"}},
	{City{"لیون", "LYS"}, []string{"لیون"}},
	{City{"مادرید", "MAD"}, []string{"مادرید"}},
	{City{"مارسی", "MRS"}, []string{"مارسی"}},
	{City{"مالاگا", "AGP"}, []string{"مالاگا"}},
	{City{"مدفورد", "MFR"}, []string{"مدفورد"}},
	{City{"مزارشریف", "MZR"}, []string{"مزارشریف"}},
	{City{"مسقط", "MCT"}, []string{"مسقط"}},
	{City{"مسکو", "MOW"}, []string{"مسکو"}},
	{City{"ملبورن", "MEL"}, []string{"ملبورن"}},
	{City{"ممفیس", "MEM"}, []string{"ممفیس"}},
	{City{"منامه", "BAH"}, []string{"منامه"}},
	{City{"منچستر", "MAN"}, []string{"منچستر"}},
	{City{"مندوزا", "MDZ"}, []string{"مندوزا"}},
	{City{"موریستاون", "MMU"}, []string{"موریستاون"}},
	{City{"موستار", "OMO"}, []string{"موستار"}},
	{City{"موصل", "OSM"}, []string{"موصل"}},
	{City{"موگیلف", "MVQ"}, []string{"موگیلف"}},
	{City{"مونترال", "YUL"}, []string{"مونترال"}},
	{City{"مونتروز", "MTJ"}, []string{"مونتروز"}},
	{City{"مونیخ", "MUC"}, []string{"مونیخ"}},
	{City{"میامی", "MIA"}, []string{"میامی"}},
	{City{"میلان", "MXP"}, []string{"میلان"}},
	{City{"مینسک", "MSQ"}, []string{"مینسک"}},
	{City{"مینیاپولیس", "MSP"}, []string{"مینیاپولیس"}},
	{City{"ناپل", "NAP"}, []string{"ناپل"}},
	{City{"ناتیتینگو", "NAE"}, []string{"ناتیتینگو"}},
	{City{"ناسائو", "NAS"}, []string{"ناسائو"}},
	{City{"ناکسویل", "TYS"}, []string{"ناکسویل"}},
	{City{"نامیبه", "MSZ"}, []string{"نامیبه"}},
	{City{"نانتاکت", "ACK"}, []string{"نانتاکت"}},
	{City{"نانجینگ", "NKG"}, []string{"نانجینگ"}},
	{City{"نجف", "NJF"}, []string{"نجف"}},
	{City{"نخجوان", "NAJ"}, []string{"نخجوان"}},
	{City{"نشویل", "BNA"}, []string{"نشویل"}},
	{City{"نورفولک", "ORF"}, []string{"نورفولک"}},
	{City{"نیواورلئان", "MSY"}, []string{"نیواورلئان"}},
	{City{"نیوکاسل", "NCL"}, []string{"نیوکاسل"}},
	{City{"نیویورک", "NYC"}, []string{"نیویورک"}},
	{City{"واشینگتن", "WAS"}, []string{"واشینگتن"}},
	{City{"والنسیا", "VLC"}, []string{"والنسیا"}},
	{City{"ورچستر", "ORH"}, []string{"ورچستر"}},
	{City{"وست پالم بیچ", "PBI"}, []string{"وست پالم بیچ"}},
	{City{"ولدوستا", "VLD"}, []string{"ولدوستا"}},
	{City{"ونکوور", "YVR"}, []string{"ونکوور"}},
	{City{"ونیز", "VCE"}, []string{"ونیز"}},
	{City{"ویلمینگتون", "ILM"}, []string{"ویلمینگتون"}},
	{City{"وین", "VIE"}, []string{"وین"}},
	{City{"وینیارد هیون", "MVY"}, []string{"وینیارد هیون"}},
	{City{"وینیپگ", "YWG"}, []string{"وینیپگ"}},
	{City{"هالیفاکس", "YHZ"}, []string{"هالیفاکس"}},
	{City{"هامبورگ", "HAM"}, []string{"هامبورگ"}},
	{City{"هت یای", "HDY"}, []string{"هت یای"}},
	{City{"هرات", "HEA"}, []string{"هرات"}},
	{City{"هریسبورگ", "MDT"}, []string{"هریسبورگ"}},
	{City{"هلسینکی", "HEL"}, []string{"هلسینکی"}},
	{City{"هنگ کنگ", "HKG"}, []string{"هنگ کنگ", "هنگ‌کنگ"}},
	{City{"هومر", "HOM"}, []string{"هومر"}},
	{City{"هونولولو", "HNL"}, []string{"هونولولو"}},
	{City{"هیلو", "ITO"}, []string{"هیلو"}},
	{City{"هیوستون", "IAH"}, []string{"هیوستون"}},
	{City{"یاکیما", "YKM"}, []string{"یاکیما"}},
	{City{"یتسبورگ", "PIT"}, []string{"یتسبورگ"}},
	{City{"یودون تانی", "UTH"}, []string{"یودون تانی"}},
	{City{"یوما", "YUM"}, []string{"یوما"}}}
